pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('', views.index, name="home"),
    path('oranges', views.oranges, name="oranges"),
    path('oranges/<int:id>', views.orange, name="orange"),
    path('about-us', views.aboutUs, name="about-us"),
    path('contact-us', views.contactUs, name="contact-us"),
    path('handle-contact-us', views.handleContactUs, name="handle-contact-us"),
    path('login', views.authLogin, name="login"),
    path('signup', views.authSignup, name="signup"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('logout', views.logout, name="logout"),
    path('getProfileInfo', views.getProfileInfo, name="profileInfo"),
    path('getProfileVehicles', views.getProfileVehicles, name="profileVehicles")
]

vehicleHire/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('auth/', include('orangeFarmers.urls')),
    path('oranges/', include('oranges.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/partials/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <!-- Google icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- MDB icons -->
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css"
    rel="stylesheet"
    />
    <!-- Bootstrap core CSS -->
    <link href="/media/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="/media/css/fontawesome.css">
    <link rel="stylesheet" href="/media/css/style.css">
    <link rel="stylesheet" href="/media/css/owl.css">
    <link rel="stylesheet" href="/media/css/custom.css">

    {% block title %}
    <title>Orange trace</title>
    <meta  name="twitter:card" content="summary_large_image" />
    <meta  name="og:type" content="website" />
    <meta  name="og:url" content="https://orange-hire.herokuapp.com" />
    <meta  name="og:title" content="VehicleHire" />
    <meta  name="og:description" content="Joining the gap between orange owners and orange customers" />
    {% endblock %}
</head>
<body>
    {% include './header.html' %}
    {% block content %}
    {% endblock %}
    {% include './footer.html' %}
    <!-- Bootstrap core JavaScript -->
    <script src="/media/vendor/jquery/jquery.min.js"></script>
    <script src="/media/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Additional Scripts -->
    <script src="/media/js/custom.js"></script>
    <script src="/media/js/owl.js"></script>
</body>
</html>

templates/partials/footer.html
<footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="inner-content">
            <p>Orange-trace © 2021</p>
          </div>
        </div>
      </div>
    </div>
  </footer>

templates/partials/header.html
<!-- Header -->
<header class="">
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <a class="navbar-brand" href="{% url 'pages:home' %}"><h2>Orange <em>trace</em></h2></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto" id="nav-list">

          <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:home' %}">Home
                  <span class="sr-only">(current)</span>
                </a>
            </li>

            <li class="nav-item"><a class="nav-link" href="{% url 'pages:oranges' %}">Oranges</a></li>

            <li class="nav-item"><a class="nav-link" href="{% url 'pages:about-us' %}">About Us</a></li>

            <li class="nav-item"><a class="nav-link" href="{% url 'pages:contact-us' %}">Contact Us</a></li>


        </ul>
      </div>
    </div>
  </nav>
  <!-- External JS -->
  <script src="/media/vendor/jquery/jquery.min.js" type="text/javascript"></script>
  <script src="/media/js/nav.js" type="text/javascript"></script>
  <!-- End of external JS-->
</header>
<!-- End of header-->