oranges/urls.py
from django.urls import path
from . import views

app_name = "oranges"

urlpatterns = [
    path('add-orange', views.handleAddVehicle, name="add-orange"),
    path('delete-orange', views.deleteVehicle, name="delete-orange"),
    path('update-hired-status', views.updateHiredStatus, name="update-hired-status")
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('', views.index, name="home"),
    path('oranges', views.oranges, name="oranges"),
    path('oranges/<int:id>', views.orange, name="orange"),
    path('about-us', views.aboutUs, name="about-us"),
    path('contact-us', views.contactUs, name="contact-us"),
    path('handle-contact-us', views.handleContactUs, name="handle-contact-us"),
    path('login', views.authLogin, name="login"),
    path('signup', views.authSignup, name="signup"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('logout', views.logout, name="logout"),
    path('getProfileInfo', views.getProfileInfo, name="profileInfo"),
    path('getProfileVehicles', views.getProfileVehicles, name="profileVehicles")
]

vehicleHire/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('auth/', include('orangeFarmers.urls')),
    path('oranges/', include('oranges.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

oranges/models.py
from django.db import models
from orangeFarmers.models import OrangeFarmer
from uuid import uuid4
# Create your models here.


def vehicle_path(instance, filename):
    extname = filename.split('.')[-1]
    if instance.pk:
        filename = f"{instance.pk}.{extname}"
    else:
        filename = f"{uuid4().hex}.{extname}"
    return f"images/oranges/{filename}"


class Orange(models.Model):
    owner = models.ForeignKey(OrangeFarmer, on_delete=models.CASCADE)
    #hired = models.BooleanField(default=False)
    type = models.CharField(max_length=200)
    price = models.CharField(max_length=200)
    maturity_date = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    foreground_image = models.ImageField(
        upload_to=vehicle_path, null=False, blank=False)
    inside_image = models.ImageField(
        upload_to=vehicle_path, null=False, blank=False)
    background_image = models.ImageField(
        upload_to=vehicle_path, null=False, blank=False)
    supplier = models.CharField(max_length=100)
    supplier_location = models.CharField(max_length=100)
    grafted = models.CharField(default="petrol", max_length=100)
    reported_cases = models.IntegerField(default=4)

    def __str__(self):
        return f"{self.owner.name},{self.type},{self.model}"

oranges/views.py
from django.shortcuts import render
from django.http import JsonResponse
from orangeFarmers.models import OrangeFarmer
from .models import Orange
from os import path, pardir, remove

# Create your views here.


def handleAddVehicle(request):

    # get the data sent, post data
    owner = request.POST.get('owner')
    type = request.POST.get('type')
    price = request.POST.get('price')
    maturity_date = request.POST.get('maturity_date')
    model = request.POST.get('model')
    location = request.POST.get('location')
    supplier = request.POST.get('supplier')
    supplier_location = request.POST.get('gear_box')
    grafted = request.POST.get('grafted')
    reported_cases = request.POST.get('reported_cases')

    # get the data sent, files data
    foreground_image = request.FILES['front_image']
    inside_image = request.FILES['inside_image']
    background_image = request.FILES['back_image']

    # fetch the owner
    owner_info = OrangeFarmer.objects.get(id=owner)

    # create the orange
    Orange.objects.create(
        owner=owner_info,
        type=type,
        price=f"Ksh {price}",
        maturity_date=f"{maturity_date}",
        model=model,
        location=location,
        foreground_image=foreground_image,
        inside_image=inside_image,
        background_image=background_image,
        supplier=f"{supplier}",
        supplier_location=supplier_location,
        grafted=grafted,
        reported_cases=reported_cases
    )

    return JsonResponse({
        "message": "Orange has been added successfully"
    })


def deleteVehicle(request):
    vehicle_id = request.POST.get('orange')

    # get the orange first
    orange = Orange.objects.get(id=vehicle_id)
    # get the parent dir
    parent_dir = path.abspath(path.join(path.dirname(__file__), pardir))

    # delete the foreground image
    if(path.exists(parent_dir+"/media/"+str(orange.foreground_image))):
        remove(parent_dir+"/media/"+str(orange.foreground_image))
    # delete the inside image
    if(path.exists(parent_dir+"/media/"+str(orange.inside_image))):
        remove(parent_dir+"/media/"+str(orange.inside_image))
    # delete the foreground image
    if(path.exists(parent_dir+"/media/"+str(orange.background_image))):
        remove(parent_dir+"/media/"+str(orange.background_image))

    # delete the orange from db
    Orange.objects.filter(id=vehicle_id).delete()

    # return a response
    return JsonResponse({
        "message": "Orange deleted successfully"
    })


def updateHiredStatus(request):
    orange = request.POST.get('orange')

    # update the orange hired status
    initial_vehicle = Orange.objects.get(id=orange)
    initial_vehicle.hired = True
    initial_vehicle.save()

    # return a response
    return JsonResponse({
        "message": "Status updated successfully"
    })

templates/pages/about-us.html
{% extends 'partials/base.html' %}

{% block title %}
<title>Orange trace | About us</title>
{% endblock %}

{% block content%}
 <!-- Page Content -->
 <div class="page-heading about-heading header-text" style="background-image: url(/media/images/heading-1.jpg);">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="text-content">
            <h4>about us</h4>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="best-features about-features">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="section-heading">
            <h2>Tracing an orange made easier!</h2>
          </div>
        </div>
        <div class="col-md-6">
          <div class="right-image">
            <img src="/media/images/abt.jpg" width="570" height="350" alt="">
          </div>
        </div>
        <div class="col-md-6">
          <div class="left-content">
            <h4>What we do</h4>
            <p>
                We enable consumers to trace oranges with ease. We link orange consumers
                with orange farmers who have partenered with us.
                <br>
                Our work is to handle the gap between potential consumers
                and partenered orange farmers.
            </p>
            <ul class="social-icons">
              <li><a href="https://facebook.com"><i class="fa fa-facebook"></i></a></li>
              <li><a href="https://twitter.com"><i class="fa fa-twitter"></i></a></li>
              <li><a href="https://instagram.com"><i class="fa fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

{% include '../components/call-to-action.html' %}
{% endblock %}

templates/pages/contact-us.html
{% extends 'partials/base.html' %}

{% block title %}
<title>Orange trace | Contact us</title>
{% endblock %}

{% block content%}
<!-- Page Content -->
<div class="page-heading contact-heading header-text" style="background-image: url(/media/images/heading-4.jpg);">
<div class="container">
    <div class="row">
    <div class="col-md-12">
        <div class="text-content">
        <h2>Contact Us</h2>
        </div>
    </div>
    </div>
</div>
</div>
<div class="send-message">
<div class="container">
    <div class="row">
    <div class="col-md-12">
        <div class="section-heading">
        <h2>Send us a Message</h2>
        </div>
    </div>
    <div class="col-md-8">
        <div class="contact-form">
        <form id="contact-us-form" action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="alert alert-success" id="contact-us-form-alert" style="display: none;"></div>
                </div>
            </div>
            <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <fieldset>
                <input name="name" type="text" class="form-control" id="name-input" placeholder="Full Name" required>
                </fieldset>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12">
                <fieldset>
                <input name="email" type="text" class="form-control" id="email-input" placeholder="E-Mail Address" required>
                <small id="email-input-error" class="text-danger"></small>
                </fieldset>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12">
                <fieldset>
                <input name="subject" type="text" class="form-control" id="subject-input" placeholder="Subject" required>
                </fieldset>
            </div>
            <div class="col-lg-12">
                <fieldset>
                <textarea name="message" rows="6" class="form-control" id="message-input" placeholder="Your Message" required></textarea>
                </fieldset>
            </div>
            <div class="col-lg-12">
                <fieldset>
                <button type="submit" id="contact-us-form-submit" class="filled-button">Send Message</button>
                </fieldset>
            </div>
            </div>
        </form>
        </div>
    </div>
    </div>
</div>
<!-- Scripts -->
<script type="text/javascript">window.CSRF_TOKEN="{{csrf_token}}"</script>
<script type="text/javascript" src="/media/js/contact-us.js"></script>
</div>
{% endblock %}

templates/pages/dashboard.html
{% extends 'partials/base.html' %}

{% block title%}
<title>Dashboard</title>
<link href="/media/css/custom.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="dashboard-section">
    {% csrf_token %}
    <div class="container">
        <div class="row">
        <div class="col-md-12">
            <div class="section-heading">
            <h2>Dashboard</h2>
            </div>
        </div>
        <div class="col-12 col-md-12">
            {% include '../components/dashboard-profile-info.html' %}
        </div>
        <div class="col-12 col-md-12">
            {% include '../components/dashboard-oranges.html' %}
        </div>
        </div>
    </div>
    <!-- External Js-->
    <script src="/media/vendor/jquery/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
    <script src="/media/js/dashboard/index.js" type="text/javascript"></script>
</div>
{% endblock %}

templates/pages/home.html
{% extends 'partials/base.html' %}

{% block title %}
<title>Orange trace</title>
{% endblock %}

{% block content%}
{% include '../components/home-banner.html' %}
<div class="latest-products">
<div class="container">
    <div class="row">
    <div class="col-md-12">
        <div class="section-heading">
        <h2>Featured farmers</h2>
        <a href="{% url 'pages:oranges' %}">view more <i class="fa fa-angle-right"></i></a>
        </div>
    </div>
    {% for orange in oranges %}
    <div class="col-lg-4 col-md-6">
        <div class="product-item">
        <a href="{% url 'pages:orange' orange.id %}"><img src="/media/{{orange.foreground_image}}" alt="{{orange.model}}"></a>
        <div class="down-content">
            <a href="{% url 'pages:orange' orange.id %}"><h4>{{orange.type}}, {{orange.supplier}}</h4></a>

            <h6>{{orange.price}}</h6>

            <small>
            <strong title="Author"><i class="fa fa-dashboard"></i>{{orange.maturity_date}} </strong> &nbsp;&nbsp;&nbsp;&nbsp;
            <strong title="EngineSize"><i class="fa fa-cube"></i>{{orange.supplier}}</strong>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong title="Location"><i class="material-icons"></i>{{orange.location | title}}</strong>
            </small>


        </div>
        <div class="down-actions">
            <a href="{% url 'pages:orange' orange.id %}" class="filled-button">
                trace now
            </a>
        </div>
        </div>
    </div>
    {% endfor %}
    </div>
</div>
</div>
{% include '../components/call-to-action.html' %}
{% endblock %}

templates/pages/orange.html
{% extends 'partials/base.html' %}

{% block title %}
<title> OrangeTrace | Oranges</title>
{% endblock %}

{% block content %}
<!--Start of page content-->
<div class="page-heading about-heading header-text" style="background-image: url(/media/images/heading-6.jpg);">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="text-content">
            <h4>{{orange.type}},{{orange.model}}</h4>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="products">
<div class="container">
    <div class="row">
    <div class="col-md-6">
        <div>
        <img src="/media/{{orange.foreground_image}}" alt="{{orange.model}}" class="img-fluid wc-image">
        </div>
        <br>
        <div class="row">
        <div class="col-sm-4 col-6">
            <div>
            <img src="/media/{{orange.inside_image}}" alt="{{orange.model}}" class="img-fluid">
            </div>
            <br>
        </div>
        <div class="col-sm-4 col-6">
            <div>
            <img src="/media/{{orange.background_image}}" alt="{{orange.model}}" class="img-fluid">
            </div>
            <br>
        </div>
        </div>
    </div>

    <div class="col-md-6">
        <form action="#" method="post" class="form">
        <ul class="list-group list-group-flush">

            <li class="list-group-item">
                <div class="clearfix">
                    <span class="pull-left">Type</span>

                    <strong class="pull-right">{{orange.type}}</strong>
                </div>
            </li>

            <li class="list-group-item">
                <div class="clearfix">
                    <span class="pull-left"> Planting Date</span>

                    <strong class="pull-right">{{orange.model}}</strong>
                </div>
            </li>

            <li class="list-group-item">
                <div class="clearfix">
                    <span class="pull-left">Maturity date</span>

                    <strong class="pull-right">{{orange.maturity_date}}</strong>
                </div>
            </li>

            <li class="list-group-item">
                <div class="clearfix">
                    <span class="pull-left">Grafted</span>

                    <strong class="pull-right">{{orange.grafted}}</strong>
                </div>
            </li>

            <li class="list-group-item">
                <div class="clearfix">
                    <span class="pull-left">Supplier</span>

                    <strong class="pull-right">{{orange.supplier}}</strong>
                </div>
            </li>


            <li class="list-group-item">
                <div class="clearfix">
                    <span class="pull-left">Supplier location</span>

                    <strong class="pull-right">{{orange.supplier_location | title}}</strong>
                </div>
            </li>

            <li class="list-group-item">
                <div class="clearfix">
                    <span class="pull-left">Reported cases</span>

                    <strong class="pull-right">{{orange.reported_cases}}</strong>
                </div>
            </li>

            <li class="list-group-item">
                <div class="clearfix">
                    <span class="pull-left">Safety status</span>

                  <strong class="pull-right">
                        {% if orange.hired %} Already hired {% else %} pending... {% endif %}
                    </strong>
                </div>
            </li>
        </ul>
        </form>
    </div>
    </div>
</div>
</div>

<div class="section">
<div class="container">
    <div class="row">
    <div class="col-md-6">
        <div class="section-heading">
        <h2>Contact Details</h2>
        </div>

        <div class="left-content">
        <p>
            <span>Name</span>

            <br>

            <strong>{{orange.owner.name}}</strong>
        </p>

        <p>
            <span>Phone</span>

            <br>

            <strong>
            <a href="tel:{{orange.owner.phone}}">{{orange.owner.phone}}</a>
            </strong>
        </p>

        <p>
            <span>Email</span>

            <br>

            <strong>
            <a href="mailto:{{orange.owner.email}}">{{orange.owner.email}}</a>
            </strong>
        </p>
        </div>
    </div>
    </div>
</div>
</div>

<!--End of page content-->
{% include '../components/call-to-action.html' %}
{% endblock %}

templates/pages/oranges.html
{% extends 'partials/base.html' %}

{% block title %}
<title>Orange trace | Oranges</title>
{% endblock %}

{% block content%}
<!-- Page Content -->
<div class="page-heading about-heading header-text" style="background-image: url(/media/images/heading-6.jpg);">
<div class="container">
    <div class="row">
    <div class="col-md-12">
        <div class="text-content">
        <h2>Oranges</h2>
        </div>
    </div>
    </div>
</div>
</div>

<div class="products">
<div class="container">
    <div class="row">
    <div class="col-md-3">
        <div class="contact-form">
            <form action="#">



                <label>Type:</label>

                <select class="form-control" id="type-select-input">
                    <option value="">-- All --</option>
                </select>

                <label>Planting Date:</label>

                <select class="form-control" id="model-select-input">
                    <option value="">-- All --</option>
                </select>

                <label>Price:</label>

                <select class="form-control" id="price-select-input">
                    <option value="">-- All --</option>
                </select>

                <label>Maturity date:</label>

                <select class="form-control" id="maturity_date-select-input">
                    <option value="">-- All --</option>
                </select>

                <label>Supplier:</label>

                <select class="form-control" id="engine-size-input">
                    <option value="">-- All --</option>
                </select>

                <label>Supplier Location:</label>

                <select class="form-control" id="grafted-input">
                    <option value="">-- All --</option>
                </select>

                <label>Safety status:</label>

                <select class="form-control" id="gear-box-input">
                    <option value="">-- All --</option>
                </select>

                <label>Reported cases:</label>

                <select class="form-control" id="number-of-seats-input">
                    <option value="">-- All --</option>
                </select>

            </form>
        </div>
    </div>

    <div class="col-md-9">
        <div class="row" id="orange-data-content">
        </div>
    </div>
    </div>
</div>
<!-- External Js -->
<script src="/media/vendor/jquery/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
    let oranges = '{{ vehicles_json|safe }}';
</script>
<script src="/media/js/oranges.js" type="text/javascript"></script>

</div>
{% include '../components/call-to-action.html' %}
{% endblock %}